# Generated by Django 5.0.4 on 2024-04-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('highest_degree', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('wait_time', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('number_of_patients', models.IntegerField()),
                ('satisfaction_level', models.IntegerField()),
            ],
        ),
    ]
