# Generated by Django 5.0.4 on 2024-05-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_doctor_specialization'),
    ]

    operations = [
    ]
